Added configuration to exclude kotlinx.coroutines from mockk's dependencies
mockk's dependencies include kotlinx.coroutines.
However, IntelliJ Platform also bundles kotlinx.coroutines.
Therefore, kotlinx.coroutines must be used from the Platform version.

If mockk's version is utilized, the following error occurs:
'void kotlinx.coroutines.debug.internal.DebugProbesImpl.install$kotlinx_coroutines_core()'
java.lang.NoSuchMethodError: 'void kotlinx.coroutines.debug.internal.DebugProbesImpl.install$kotlinx_coroutines_core()'